apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: transactions-xa
spec:
  applicationImage: "image-registry.openshift-image-registry.svc:5000/mywfly/transactions-xa:latest"
  replicas: 1
  bootableJar: true
  env:
    - name: POSTGRESQL_DATASOURCE
      value: PostgreSQLDS
    - name: POSTGRESQL_SERVICE_HOST
      value: postgresql
    - name: POSTGRESQL_SERVICE_PORT
      value: '5432'
    - name: POSTGRESQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: database-name
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: username
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: password
    # jdk11 bootable jar needs more metaspace than default
    - name: GC_MAX_METASPACE_SIZE
      value: '256'
    - name: GC_METASPACE_SIZE
      value: '96'
