apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: transactions-xa
spec:
  applicationImage: "image-registry.openshift-image-registry.svc:5000/mywfly/transactions-xa:latest"
  replicas: 1
  # false as running with standalone WildFly
  bootableJar: false
  env:
    # when the s2i scripts does not work as you wish the debugging of their output may help
    # - name: SCRIPT_DEBUG
    #  value: 'true'
    # PostgreSQL env variables for XA datasource creation driven by s2i scripts (not by galleon layers!)
    # Galleon layer defines only postgresql-driver and thus it does not provide the datasource creation
    - name: DB_SERVICE_PREFIX_MAPPING
      value: 'PostgreSQLDS-postgresql=PG'
    - name: PG_NONXA
      value: 'false'
    - name: POSTGRESQLDS_POSTGRESQL_SERVICE_HOST
      value: 'postgresql'
    - name: POSTGRESQLDS_POSTGRESQL_SERVICE_PORT
      value: '5432'
    - name: PG_JNDI
      value: 'java:jboss/datasources/PostgreSQLDS'
    - name: PG_DRIVER
      value: 'postgresql'
    - name: PG_DATABASE
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: database-name
    - name: PG_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: username
    - name: PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: password
    # Narayana JDBC objectstore creation via s2i env variables
    - name: TX_DATABASE_PREFIX_MAPPING
      value: 'PostgresJdbcObjectStore-postgresql=PG_OBJECTSTORE'
    - name: POSTGRESJDBCOBJECTSTORE_POSTGRESQL_SERVICE_HOST
      value: 'postgresql'
    - name: POSTGRESJDBCOBJECTSTORE_POSTGRESQL_SERVICE_PORT
      value: '5432'
    - name: PG_OBJECTSTORE_JNDI
      value: 'java:jboss/datasources/PostgresJdbc'
    - name: PG_OBJECTSTORE_DRIVER
      value: 'postgresql'
    - name: PG_OBJECTSTORE_DATABASE
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: database-name
    - name: PG_OBJECTSTORE_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: username
    - name: PG_OBJECTSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: password
    # no need for default DS provided by H2
    - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
      value: 'false'
    # jdk11 bootable jar needs more metaspace than default
    - name: GC_MAX_METASPACE_SIZE
      value: '256'
    - name: GC_METASPACE_SIZE
      value: '96'
