= Postgresql WildFly OpenShift example with XA trasactions

== Bare metal WildFly deployment

* `mvn clean package` creates the `war` file
* take WildFly runtime and copy the `war` to `$JBOSS_HOME/standalone/deployments`
* download the PostgreSQL JDBC driver (e.g. from https://jdbc.postgresql.org)
* start PostgreSQL server
+
[source,sh]
----
# a possible way to run PostgreSQL on localhost to test
docker run -p 5432:5432 --rm  -ePOSTGRES_DB=test -ePOSTGRES_USER=test -ePOSTGRES_PASSWORD=test\
  postgres:9.4 -c max-prepared-transactions=110 -c log-statement=all
----
+
* setup WFLY with driver and with adding the datasource
+
[source,sh]
----
cd $JBOSS_HOME
# driver installation
./bin/jboss-cli.sh "embed-server,\
  module add --name=org.postgresql.jdbc --resources=<path-to-jar>/postgresql.jar --dependencies=javax.api\,javax.transaction.api"
./bin/jboss-cli.sh "embed-server --server-config=standalone.xml,\
 /subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql,driver-module-name=org.postgresql.jdbc,driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)"
# adding xa-datasource
./bin/jboss-cli.sh "embed-server --server-config=standalone.xml,\
  xa-data-source add --name=PostgreSQLDS --driver-name=postgresql --jndi-name=java:jboss/datasources/PostgreSQLDS --user-name=test --password=test --xa-datasource-properties=ServerName=localhost,\
  /subsystem=datasources/xa-data-source=PostgreSQLDS/xa-datasource-properties=PortNumber:add(value=5432),\
  /subsystem=datasources/xa-data-source=PostgreSQLDS/xa-datasource-properties=DatabaseName:add(value=test)"
----
* start the WildFly and use curl to invoke rest endpoints
+
[source,sh]
----
# start WildFly
cd $JBOSS_HOME
./bin/standalone.sh

# run HTTP requests
curl -XPOST -i http://localhost:8080/transactions-xa-3.0.0.Beta2-SNAPSHOT/tasks/title/name
curl -XGET -i http://localhost:8080/transactions-xa-3.0.0.Beta2-SNAPSHOT/tasks/id/{id}
curl -XGET -i http://localhost:8080/transactions-xa-3.0.0.Beta2-SNAPSHOT/tasks/
# transaction in heuristics (may be checked via jboss cli)
curl -XPOST -i http://localhost:8080/transactions-xa-3.0.0.Beta2-SNAPSHOT/tasks/title/name-to-fail/fail
./bin/jboss-cli.sh -c --commands='/subsystem=transactions/log-store=log-store:probe,/subsystem=transactions/log-store=log-store:read-resource(recursive=true, include-runtime=true)'
----

== OpenShift WildFly S2I image deployment

* Start the PostgreSQL on OpenShift
+
NOTE: We cannot use the simple `new-app` command as we need to permit XA transactions
      with `max-prepared-transactions`. The args of command is used for it in PostgreSQL image. +
      The `new-app` does not provide a way to pass the args.
+
[source,sh]
----
# using username/password as 'admin/admin' with database 'sampledb'
oc create -f config/postgresql.deployment.yaml
----
+
* Configure the WildFly image stream and chain build for OpenShift
+
[source,sh]
----
# Create WildFly build and runtime image streams
oc create -f config/wildfly-image-stream.json
# Upload the application build template named wildfly-s2i.
oc create -f config/wildfly-chain-build-template.json
----
+
* Invoke the build
+
[source,sh]
----
# Getting the source to build from GitHub
oc new-app --template=wildfly-s2i -p IMAGE_STREAM_NAMESPACE=$(oc project -q) \
  -p APPLICATION_NAME="transactions-xa" \
  -p SOURCE_REPOSITORY_URL=https://github.com/wildfly-extras/wildfly-jar-maven-plugin/.git \
  -p SOURCE_REPOSITORY_REF=master -p CONTEXT_DIR=examples/transactions-xa
----


== OpenShift WildFly bootable jar

* mvn package -Popenshift
* mkdir os && cp target/postgresql-bootable.jar os/
* Import the OpenJDK 11 image to run the Java application, create the image stream and deployment:
```
oc import-image ubi8/openjdk-11 --from=registry.redhat.io/ubi8/openjdk-11 --confirm

oc new-build --strategy source --binary --image-stream openjdk-11 --name wf-postgresql

oc start-build wf-postgresql --from-dir ./os/

oc new-app --name wf-postgresql-app \
    --env POSTGRESQL_USER=admin \
    --env POSTGRESQL_PASSWORD=admin \
    --env POSTGRESQL_SERVICE_HOST=database-server \
    --env POSTGRESQL_SERVICE_PORT=5432 \
    --env POSTGRESQL_DATABASE=sampledb \
    --env GC_MAX_METASPACE_SIZE=256 \
    --env GC_METASPACE_SIZE=96 \
    wf-postgresql

oc expose svc/wf-postgresql-app
```
* Add a new task:
```
curl -X POST http://$(oc get route wf-postgresql-app --template='{{ .spec.host }}')/tasks/title/foo`

* Get all the tasks:
`curl http://$(oc get route wf-postgresql-app --template='{{ .spec.host }}')`
