= Postgresql WildFly OpenShift example with XA trasactions testing

== Bare metal WildFly deployment

* `mvn clean package` creates the `war` file
* take WildFly runtime and copy the `war` to `$JBOSS_HOME/standalone/deployments`
* download the PostgreSQL JDBC driver (e.g. from https://jdbc.postgresql.org)
* start PostgreSQL server
+
[source,sh]
----
# a possible way to run PostgreSQL on localhost to test
docker run -p 5432:5432 --rm  -ePOSTGRES_DB=test -ePOSTGRES_USER=test -ePOSTGRES_PASSWORD=test\
  postgres:9.4 -c max-prepared-transactions=110 -c log-statement=all
----
+
* setup WFLY with driver and with adding the datasource
+
[source,sh]
----
cd $JBOSS_HOME
# driver installation
./bin/jboss-cli.sh "embed-server,\
  module add --name=org.postgresql.jdbc --resources=<path-to-jar>/postgresql.jar --dependencies=javax.api\,javax.transaction.api"
./bin/jboss-cli.sh "embed-server --server-config=standalone.xml,\
 /subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql,driver-module-name=org.postgresql.jdbc,driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)"
# adding xa-datasource
./bin/jboss-cli.sh "embed-server --server-config=standalone.xml,\
  xa-data-source add --name=PostgreSQLDS --driver-name=postgresql --jndi-name=java:jboss/datasources/PostgreSQLDS --user-name=test --password=test --xa-datasource-properties=ServerName=localhost,\
  /subsystem=datasources/xa-data-source=PostgreSQLDS/xa-datasource-properties=PortNumber:add(value=5432),\
  /subsystem=datasources/xa-data-source=PostgreSQLDS/xa-datasource-properties=DatabaseName:add(value=test)"
----

Openshift binary build and deployment
=====================================

Create and configure a PostgreSQL data base server:

```
oc new-app --name database-server \
     --env POSTGRESQL_USER=admin \
     --env POSTGRESQL_PASSWORD=admin \
     --env POSTGRESQL_DATABASE=sampledb \
     postgresql
```

* mvn package -Popenshift
* mkdir os && cp target/postgresql-bootable.jar os/
* Import the OpenJDK 11 image to run the Java application, create the image stream and deployment:
```
oc import-image ubi8/openjdk-11 --from=registry.redhat.io/ubi8/openjdk-11 --confirm

oc new-build --strategy source --binary --image-stream openjdk-11 --name wf-postgresql

oc start-build wf-postgresql --from-dir ./os/

oc new-app --name wf-postgresql-app \
    --env POSTGRESQL_USER=admin \
    --env POSTGRESQL_PASSWORD=admin \
    --env POSTGRESQL_SERVICE_HOST=database-server \
    --env POSTGRESQL_SERVICE_PORT=5432 \
    --env POSTGRESQL_DATABASE=sampledb \
    --env GC_MAX_METASPACE_SIZE=256 \
    --env GC_METASPACE_SIZE=96 \
    wf-postgresql

oc expose svc/wf-postgresql-app
```
* Add a new task:
```
curl -X POST http://$(oc get route wf-postgresql-app --template='{{ .spec.host }}')/tasks/title/foo`

* Get all the tasks:
`curl http://$(oc get route wf-postgresql-app --template='{{ .spec.host }}')`
